#ifndef SOCIALNETWORKWINDOW_H
#define SOCIALNETWORKWINDOW_H

#include <QMainWindow>
#include "network.h"
#include "user.h"
#include "post.h"

QT_BEGIN_NAMESPACE
namespace Ui {
class SocialNetworkWindow;
}
QT_END_NAMESPACE

// Main window class for the social network application
class SocialNetworkWindow : public QMainWindow
{
    Q_OBJECT

public:
    // Constructor and destructor
    SocialNetworkWindow(QWidget *parent = nullptr);
    ~SocialNetworkWindow();

    // UI event handlers
    void loginButtonClick();       // Handle login button press
    void backButtonClick();        // Return to logged-in user's profile
    void addFriend();              // Add a friend for the displayed user
    void addPost();                // Show post input field
    void Post();                   // Create a new post
    void displayPage(User* curUser);  // Update UI for the given user
    void seeReactions();           // Show buttons to view reactions for posts

    // Post selection button handlers for viewing reactions
    void b1Click();
    void b2Click();
    void b3Click();
    void b4Click();
    void b5Click();

    void rDoneClick();             // Hide reactions display

    // Post selection button handlers for adding reactions
    void addReactionClick();
    void b11Click();
    void b22Click();
    void b33Click();
    void b44Click();
    void b55Click();

    // Reaction button handlers
    void likeButtonClick();
    void heartButtonClick();
    void laughButtonClick();

private:
    Ui::SocialNetworkWindow *ui;   // UI pointer generated by Qt Designer
    User* loggedInUser;            // Pointer to the currently logged-in user
    User* userDisplayed;           // Pointer to the currently displayed user profile
    Network* currentNetwork;       // Pointer to the network object
    Post* curPost;                 // Pointer to the currently selected post for reactions
};

#endif // SOCIALNETWORKWINDOW_H
